// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TenantAPI.Models;

namespace TenantAPI.Migrations
{
    [DbContext(typeof(TenantAPIContext))]
    [Migration("20200507010722_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TenantAPI.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApartmentName")
                        .IsRequired();

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<bool>("IsBackgroundChecked");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = 1,
                            ApartmentName = "Baker Apartments",
                            ApartmentNumber = "221B",
                            Email = "assistant@holmes.com",
                            FirstName = "John",
                            IsBackgroundChecked = true,
                            LastName = "Watson",
                            Phone = "4477009999"
                        },
                        new
                        {
                            TenantId = 2,
                            ApartmentName = "Baker Apartments",
                            ApartmentNumber = "221B",
                            Email = "detective@holmes.com",
                            FirstName = "Sherlock",
                            IsBackgroundChecked = true,
                            LastName = "Holmes",
                            Phone = "4477009999"
                        },
                        new
                        {
                            TenantId = 3,
                            ApartmentName = "Baker Apartments",
                            ApartmentNumber = "221A",
                            Email = "housekeeper@holmes.com",
                            FirstName = "Mrs",
                            IsBackgroundChecked = true,
                            LastName = "Hudson",
                            Phone = "4477008888"
                        },
                        new
                        {
                            TenantId = 4,
                            ApartmentName = "Downing Apartments",
                            ApartmentNumber = "303",
                            Email = "specialist@morgue.com",
                            FirstName = "Molly",
                            IsBackgroundChecked = true,
                            LastName = "Hooper",
                            Phone = "4476001111"
                        },
                        new
                        {
                            TenantId = 5,
                            ApartmentName = "Stonyhurst Place",
                            ApartmentNumber = "V20",
                            Email = "mastermind@villain.com",
                            FirstName = "James",
                            IsBackgroundChecked = false,
                            LastName = "Moriarty",
                            Phone = "4470004444"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
